alter table public.events
  add column if not exists user_id integer references public.users(id) on delete set null;

create table if not exists public.community_comments (
  id integer generated by default as identity primary key,
  post_id integer not null references public.community_posts(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  author_name text not null,
  body text not null,
  created_at timestamp without time zone default now()
);

create table if not exists public.community_post_likes (
  post_id integer not null references public.community_posts(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  created_at timestamp without time zone default now(),
  primary key (post_id, user_id)
);

create table if not exists public.event_rsvps (
  event_id integer not null references public.events(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  created_at timestamp without time zone default now(),
  primary key (event_id, user_id)
);

create index if not exists idx_events_user_id on public.events(user_id);
create index if not exists idx_community_comments_post_id on public.community_comments(post_id);
create index if not exists idx_community_comments_user_id on public.community_comments(user_id);
create index if not exists idx_community_post_likes_user_id on public.community_post_likes(user_id);
create index if not exists idx_event_rsvps_user_id on public.event_rsvps(user_id);

alter table public.community_comments enable row level security;
alter table public.community_post_likes enable row level security;
alter table public.event_rsvps enable row level security;
