create table if not exists public.admin_roles (
  user_id integer primary key references public.users(id) on delete cascade,
  role text not null default 'moderator',
  permissions text default '{}',
  created_by integer references public.users(id) on delete set null,
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table if not exists public.moderator_invites (
  id integer generated by default as identity primary key,
  email text not null,
  invited_by integer not null references public.users(id) on delete cascade,
  approved_by integer references public.users(id) on delete set null,
  status text not null default 'pending',
  permissions text default '{}',
  created_at timestamp without time zone default now(),
  updated_at timestamp without time zone default now()
);

create table if not exists public.admin_audit_logs (
  id integer generated by default as identity primary key,
  actor_user_id integer not null references public.users(id) on delete cascade,
  action text not null,
  target_type text not null,
  target_id text,
  detail text,
  created_at timestamp without time zone default now()
);

create table if not exists public.announcements (
  id integer generated by default as identity primary key,
  title text not null,
  body text not null,
  audience text not null default 'all',
  channel text not null default 'community',
  status text not null default 'draft',
  created_by integer not null references public.users(id) on delete cascade,
  published_at timestamp without time zone,
  created_at timestamp without time zone default now()
);

create table if not exists public.support_case_notes (
  id integer generated by default as identity primary key,
  case_id integer not null references public.support_cases(id) on delete cascade,
  admin_user_id integer not null references public.users(id) on delete cascade,
  note text not null,
  created_at timestamp without time zone default now()
);

create index if not exists idx_moderator_invites_status on public.moderator_invites(status);
create index if not exists idx_admin_audit_logs_actor on public.admin_audit_logs(actor_user_id);
create index if not exists idx_admin_audit_logs_target on public.admin_audit_logs(target_type, target_id);
create index if not exists idx_announcements_status on public.announcements(status);
create index if not exists idx_support_case_notes_case_id on public.support_case_notes(case_id);

alter table public.admin_roles enable row level security;
alter table public.moderator_invites enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.announcements enable row level security;
alter table public.support_case_notes enable row level security;
